### ISSUE TITLE
mongo url

### ISSUE THREAD

**Issue by Ghani768** [Sudhi27Krishna/ESA-Backend#35]
whats mongo url

**Comment by Ghani768** [comment]
Where's the monog url
It says an mongoose error openuri() should be a string
Whats wrong could you explain as soon as possible

**Comment by Sudhi27Krishna** [comment]
> Where's the monog url
> It says an mongoose error openuri() should be a string
> Whats wrong could you explain as soon as possible 

There are a few files, without that the project won't run. Will upload it by tomorrow 12pm IST.

**Comment by Ghani768** [comment]
Please do upload asap as i want to do this project
Thanks for the project guidance bro

**Comment by Ghani768** [comment]
Please do uploadthis asap
As i am working on this project bro
Thanks for the project and execution process in YouTube
Please upload files bro

**Comment by Ghani768** [comment]
Please do uploadthis asap
As i am working on this project bro
Thanks for the project and execution process in YouTube
Please upload files bro

**Comment by Sudhi27Krishna** [comment]
Uploaded the necessary files.

**Comment by Ghani768** [comment]
bro it's loading in seat allocation 
it's not showing the exams which added
could you tell me how to fix this
should i upload an empty excel file

**Comment by Sudhi27Krishna** [comment]
Before adding the exam schedule make sure the excel file is uploaded which is provided in the readme section.

**Comment by Ghani768** [comment]
ok bro now its showing thanks
how to change block name bro 
i want to put it according to my college bro
where can i see the arrangement bro
could you give any contact details bro i need help with you insta id/telegram etc..

**Comment by Sudhi27Krishna** [comment]
> ok bro now its showing thanks
> how to change block name bro 
> i want to put it according to my college bro
> where can i see the arrangement bro

Create your own MongoDB cluster and create the required collections add the details in the collections, same to be done in the frontend part.

**Comment by Ghani768** [comment]
arrangement can be seen through only mail right bro
how do i get the arrangement to my mail
i click receive mail but it doesnt come to my mail 
bro please explain it

**Comment by Sudhi27Krishna** [comment]
> arrangement can be seen through only mail right bro
> how do i get the arrangement to my mail
> i click receive mail but it doesnt come to my mail 
> bro please explain it

It will be sent to the email id you provide during registering the user.

**Comment by Ghani768** [comment]
![Capture](https://github.com/Sudhi27Krishna/ESA-Backend/assets/174036439/b9eaecd2-fd68-47c7-8300-9700794e9952)
but while creating it says use mgits mail id 
i searched it google and i kept mymail@mgits.ac.in then only it accepted 
but i dont whats mgit mail id so how can i get it to my mail

**Comment by Sudhi27Krishna** [comment]
Before adding the exam schedule make sure the excel file is uploaded.

Yeah because of the regex created in the front end, only email ids associated with my college would work, you can do the changes as you wish.

**Comment by Ghani768** [comment]
wher's regex file bro
bro how to remove that mgits email permanently bro
could you tell me without hesitaion

**Comment by Sudhi27Krishna** [comment]
Just search src/components/Register.jsx.
Obviously if it occurs during registering it has to be there in the front end repo.

**Comment by Ghani768** [comment]
is there any option to insert all email id's 
specifically i don't know how to remove mgits.ac.in
like how can i insert any mail id like gmail.com
it's troubleshooting me
 bro like it should accept any types of mail id's
bro please help me

**Comment by Sudhi27Krishna** [comment]
> is there any option to insert all email id's 
> specifically i don't know how to remove mgits.ac.in
> like how can i insert any mail id like gmail.com
> it's troubleshooting me
>  bro like it should accept any types of mail id's
> bro please help me 

Just change the regex which accepts all types, use chatgpt. The regex is at the upper part of the jsx file, if you had seen the Register.jsx file which I mentioned earlier. Just do a little research before asking.

**Comment by Ghani768** [comment]
> > ok bro now its showing thanks
> > how to change block name bro
> > i want to put it according to my college bro
> > where can i see the arrangement bro
> 
> Create your own MongoDB cluster and create the required collections add the details in the collections, same to be done in the frontend part.

could you explain it briefly

**Comment by Sudhi27Krishna** [comment]
No time, search about it on YouTube.

**Comment by Ghani768** [comment]
> No time, search about it on YouTube.

what should i search please tell to me bro
i am student

**Comment by Sudhi27Krishna** [comment]
Just search about MongoDB cluster and collections, ask your friends or seniors.

**Comment by Ghani768** [comment]
thank you bro

**Comment by Ghani768** [comment]
Bro where's your mongodb cluster in repository

**Comment by Sudhi27Krishna** [comment]
In the .env file

**Comment by Ghani768** [comment]
Bro sorry for the inconvenience actually i didnt know this was a high class project
